# Generated by Django 5.2 on 2025-04-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=64, unique=True)),
                ('image_file', models.ImageField(upload_to='cache_images/')),
                ('prediction', models.TextField()),
                ('segments', models.JSONField()),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
